[rospy.client][INFO] 2020-04-10 15:27:01,461: init_node, name[/heading_compare_node], pid[2814]
[xmlrpc][INFO] 2020-04-10 15:27:01,461: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2020-04-10 15:27:01,462: Started XML-RPC server [http://juan:37329/]
[rospy.init][INFO] 2020-04-10 15:27:01,462: ROS Slave URI: [http://juan:37329/]
[rospy.impl.masterslave][INFO] 2020-04-10 15:27:01,462: _ready: http://juan:37329/
[rospy.registration][INFO] 2020-04-10 15:27:01,463: Registering with master node http://tractor:11311/
[xmlrpc][INFO] 2020-04-10 15:27:01,463: xml rpc node: starting XML-RPC server
[rospy.init][INFO] 2020-04-10 15:27:01,562: registered with master
[rospy.rosout][INFO] 2020-04-10 15:27:01,563: initializing /rosout core topic
[rospy.rosout][INFO] 2020-04-10 15:27:01,576: connected to core topic /rosout
[rospy.simtime][INFO] 2020-04-10 15:27:01,587: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.internal][INFO] 2020-04-10 15:27:01,680: topic[/tcpvel] adding connection to [http://juan:36399/], count 0
[rospy.internal][INFO] 2020-04-10 15:27:01,801: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2020-04-10 15:27:53,360: topic[/heading] adding connection to [/rostopic_2852_1586532472795], count 0
[rosout][WARNING] 2020-04-10 15:28:57,720: Inbound TCP/IP connection failed: connection from sender terminated before handshake header received. 0 bytes were received. Please check sender for additional details.
[rospy.internal][ERROR] 2020-04-10 15:28:57,722: Inbound TCP/IP connection failed:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 321, in _tcp_server_callback
    header = read_ros_handshake_header(sock, StringIO(), buff_size)
  File "/usr/lib/python2.7/dist-packages/rosgraph/network.py", line 365, in read_ros_handshake_header
    raise ROSHandshakeException("connection from sender terminated before handshake header received. %s bytes were received. Please check sender for additional details."%b.tell())
ROSHandshakeException: connection from sender terminated before handshake header received. 0 bytes were received. Please check sender for additional details.

[rospy.internal][INFO] 2020-04-10 15:28:57,851: topic[/heading] removing connection to /rostopic_2852_1586532472795
[rospy.internal][WARNING] 2020-04-10 15:30:15,397: Unknown error initiating TCP/IP socket to juan:43727 (http://juan:36399/): Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/usr/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/usr/lib/python2.7/dist-packages/rosgraph/network.py", line 365, in read_ros_handshake_header
    raise ROSHandshakeException("connection from sender terminated before handshake header received. %s bytes were received. Please check sender for additional details."%b.tell())
ROSHandshakeException: connection from sender terminated before handshake header received. 0 bytes were received. Please check sender for additional details.

[rospy.internal][INFO] 2020-04-10 15:30:15,397: topic[/tcpvel] removing connection to http://juan:36399/
[rospy.core][INFO] 2020-04-10 15:30:17,256: signal_shutdown [signal-2]
[rospy.internal][INFO] 2020-04-10 15:30:18,163: topic[/rosout] removing connection to /rosout
[rospy.impl.masterslave][INFO] 2020-04-10 15:30:18,164: signal-2
[rospy.core][INFO] 2020-04-10 15:30:18,379: signal_shutdown [atexit]
[rospy.client][INFO] 2020-04-10 15:30:24,884: init_node, name[/heading_compare_node], pid[2869]
[xmlrpc][INFO] 2020-04-10 15:30:24,884: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2020-04-10 15:30:24,885: Started XML-RPC server [http://juan:36835/]
[rospy.init][INFO] 2020-04-10 15:30:24,885: ROS Slave URI: [http://juan:36835/]
[rospy.impl.masterslave][INFO] 2020-04-10 15:30:24,885: _ready: http://juan:36835/
[rospy.registration][INFO] 2020-04-10 15:30:24,886: Registering with master node http://tractor:11311/
[xmlrpc][INFO] 2020-04-10 15:30:24,886: xml rpc node: starting XML-RPC server
[rospy.init][INFO] 2020-04-10 15:30:24,985: registered with master
[rospy.rosout][INFO] 2020-04-10 15:30:24,986: initializing /rosout core topic
[rospy.rosout][INFO] 2020-04-10 15:30:25,223: connected to core topic /rosout
[rospy.simtime][INFO] 2020-04-10 15:30:27,478: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.internal][INFO] 2020-04-10 15:30:32,494: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2020-04-10 15:32:27,210: topic[/heading] adding connection to [/rostopic_2890_1586532746940], count 0
[rospy.internal][INFO] 2020-04-10 15:32:28,091: topic[/heading] removing connection to /rostopic_2890_1586532746940
[rospy.internal][INFO] 2020-04-10 15:37:14,967: topic[/heading] adding connection to [/rostopic_3022_1586533034632], count 0
[rospy.internal][INFO] 2020-04-10 15:37:52,491: topic[/heading] removing connection to /rostopic_3022_1586533034632
[rospy.internal][INFO] 2020-04-10 15:59:52,484: topic[/rosout] adding connection to [/rosout], count 1
[rospy.internal][INFO] 2020-04-10 15:59:52,485: topic[/rosout] removing connection to /rosout
[rospy.core][INFO] 2020-04-10 16:02:33,432: signal_shutdown [signal-2]
[rospy.internal][INFO] 2020-04-10 16:02:33,457: topic[/rosout] removing connection to /rosout
[rospy.impl.masterslave][INFO] 2020-04-10 16:02:33,457: signal-2
[rospy.core][INFO] 2020-04-10 16:02:34,073: signal_shutdown [atexit]
[rospy.client][INFO] 2020-04-10 16:03:33,760: init_node, name[/heading_compare_node], pid[3067]
[xmlrpc][INFO] 2020-04-10 16:03:33,761: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2020-04-10 16:03:33,761: Started XML-RPC server [http://juan:42123/]
[rospy.init][INFO] 2020-04-10 16:03:33,761: ROS Slave URI: [http://juan:42123/]
[rospy.impl.masterslave][INFO] 2020-04-10 16:03:33,761: _ready: http://juan:42123/
[rospy.registration][INFO] 2020-04-10 16:03:33,762: Registering with master node http://tractor:11311/
[xmlrpc][INFO] 2020-04-10 16:03:33,763: xml rpc node: starting XML-RPC server
[rospy.init][INFO] 2020-04-10 16:03:33,862: registered with master
[rospy.rosout][INFO] 2020-04-10 16:03:33,862: initializing /rosout core topic
[rospy.rosout][INFO] 2020-04-10 16:03:33,911: connected to core topic /rosout
[rospy.simtime][INFO] 2020-04-10 16:03:33,956: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.internal][INFO] 2020-04-10 16:03:34,188: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2020-04-10 16:03:34,230: topic[/tcpvel] adding connection to [http://juan:40943/], count 0
[rospy.internal][INFO] 2020-04-10 16:03:55,156: topic[/heading] adding connection to [/rostopic_3091_1586534634886], count 0
[rospy.internal][ERROR] 2020-04-10 16:04:17,013: Unable to initiate TCP/IP socket to juan:43001 (http://juan:40943/): Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/usr/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/usr/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2020-04-10 16:04:17,248: topic[/tcpvel] adding connection to [http://juan:46433/], count 1
[rospy.internal][WARNING] 2020-04-10 16:04:18,020: Unknown error initiating TCP/IP socket to juan:43001 (http://juan:40943/): Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2020-04-10 16:04:18,021: topic[/tcpvel] removing connection to http://juan:40943/
[rospy.internal][WARNING] 2020-04-10 16:04:26,191: Unknown error initiating TCP/IP socket to juan:35813 (http://juan:46433/): Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/usr/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/usr/lib/python2.7/dist-packages/rosgraph/network.py", line 365, in read_ros_handshake_header
    raise ROSHandshakeException("connection from sender terminated before handshake header received. %s bytes were received. Please check sender for additional details."%b.tell())
ROSHandshakeException: connection from sender terminated before handshake header received. 0 bytes were received. Please check sender for additional details.

[rospy.internal][INFO] 2020-04-10 16:04:26,191: topic[/tcpvel] removing connection to http://juan:46433/
[rospy.internal][INFO] 2020-04-10 16:04:32,019: topic[/tcpvel] adding connection to [http://juan:33063/], count 0
[rospy.internal][WARNING] 2020-04-10 16:07:13,883: Unknown error initiating TCP/IP socket to juan:32859 (http://juan:33063/): Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/usr/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/usr/lib/python2.7/dist-packages/rosgraph/network.py", line 365, in read_ros_handshake_header
    raise ROSHandshakeException("connection from sender terminated before handshake header received. %s bytes were received. Please check sender for additional details."%b.tell())
ROSHandshakeException: connection from sender terminated before handshake header received. 0 bytes were received. Please check sender for additional details.

[rospy.internal][INFO] 2020-04-10 16:07:13,883: topic[/tcpvel] removing connection to http://juan:33063/
[rospy.internal][INFO] 2020-04-10 16:07:37,254: topic[/heading] removing connection to /rostopic_3091_1586534634886
[rospy.core][INFO] 2020-04-10 16:11:58,710: signal_shutdown [signal-2]
[rospy.internal][INFO] 2020-04-10 16:12:00,940: topic[/rosout] removing connection to /rosout
[rospy.impl.masterslave][INFO] 2020-04-10 16:12:00,940: signal-2
[rospy.core][INFO] 2020-04-10 16:12:01,356: signal_shutdown [atexit]
[rospy.client][INFO] 2020-04-10 19:45:50,868: init_node, name[/heading_compare_node], pid[3573]
[xmlrpc][INFO] 2020-04-10 19:45:50,869: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2020-04-10 19:45:50,869: Started XML-RPC server [http://juan:40653/]
[rospy.init][INFO] 2020-04-10 19:45:50,870: ROS Slave URI: [http://juan:40653/]
[rospy.impl.masterslave][INFO] 2020-04-10 19:45:50,870: _ready: http://juan:40653/
[rospy.registration][INFO] 2020-04-10 19:45:50,871: Registering with master node http://tractor:11311/
[xmlrpc][INFO] 2020-04-10 19:45:50,871: xml rpc node: starting XML-RPC server
[rospy.init][INFO] 2020-04-10 19:45:50,970: registered with master
[rospy.rosout][INFO] 2020-04-10 19:45:50,970: initializing /rosout core topic
[rospy.rosout][INFO] 2020-04-10 19:45:50,984: connected to core topic /rosout
[rospy.simtime][INFO] 2020-04-10 19:45:50,993: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.internal][INFO] 2020-04-10 19:45:51,088: topic[/tcpvel] adding connection to [http://juan:45301/], count 0
[rospy.internal][INFO] 2020-04-10 19:45:51,219: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2020-04-10 19:46:57,642: topic[/heading] adding connection to [/rostopic_3700_1586548017375], count 0
[rospy.internal][INFO] 2020-04-10 19:48:06,083: topic[/heading] removing connection to /rostopic_3700_1586548017375
[rosout][WARNING] 2020-04-10 19:48:06,466: Inbound TCP/IP connection failed: connection from sender terminated before handshake header received. 0 bytes were received. Please check sender for additional details.
[rospy.internal][ERROR] 2020-04-10 19:48:06,468: Inbound TCP/IP connection failed:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 321, in _tcp_server_callback
    header = read_ros_handshake_header(sock, StringIO(), buff_size)
  File "/usr/lib/python2.7/dist-packages/rosgraph/network.py", line 365, in read_ros_handshake_header
    raise ROSHandshakeException("connection from sender terminated before handshake header received. %s bytes were received. Please check sender for additional details."%b.tell())
ROSHandshakeException: connection from sender terminated before handshake header received. 0 bytes were received. Please check sender for additional details.

[rospy.internal][INFO] 2020-04-10 19:48:47,863: topic[/heading] adding connection to [/gps_to_pose_conversion_node], count 0
[rospy.internal][INFO] 2020-04-10 19:53:02,885: topic[/heading] removing connection to /gps_to_pose_conversion_node
[rospy.internal][INFO] 2020-04-10 19:57:44,226: topic[/heading] adding connection to [/gps_to_pose_conversion_node], count 0
[rospy.internal][INFO] 2020-04-10 19:59:12,915: topic[/heading] adding connection to [/rostopic_4177_1586548752641], count 1
[rospy.internal][INFO] 2020-04-10 19:59:21,189: topic[/heading] adding connection to [/rostopic_4177_1586548752641], count 2
[rospy.internal][INFO] 2020-04-10 19:59:21,190: topic[/heading] removing connection to /rostopic_4177_1586548752641
[rospy.internal][INFO] 2020-04-10 19:59:21,484: topic[/heading] removing connection to /rostopic_4177_1586548752641
[rospy.core][INFO] 2020-04-10 20:00:01,878: signal_shutdown [signal-2]
[rospy.internal][INFO] 2020-04-10 20:00:01,905: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2020-04-10 20:00:01,906: topic[/heading] removing connection to /gps_to_pose_conversion_node
[rospy.internal][INFO] 2020-04-10 20:00:01,907: topic[/tcpvel] removing connection to http://juan:45301/
[rospy.impl.masterslave][INFO] 2020-04-10 20:00:01,907: signal-2
[rospy.internal][WARNING] 2020-04-10 20:00:01,909: Unknown error initiating TCP/IP socket to juan:46055 (http://juan:45301/): Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 558, in connect
    self.local_endpoint = self.socket.getsockname()
AttributeError: 'NoneType' object has no attribute 'getsockname'

[rospy.core][INFO] 2020-04-10 20:00:02,529: signal_shutdown [atexit]
[rospy.client][INFO] 2020-04-10 20:00:05,453: init_node, name[/heading_compare_node], pid[4196]
[xmlrpc][INFO] 2020-04-10 20:00:05,454: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2020-04-10 20:00:05,454: Started XML-RPC server [http://juan:42415/]
[rospy.init][INFO] 2020-04-10 20:00:05,454: ROS Slave URI: [http://juan:42415/]
[rospy.impl.masterslave][INFO] 2020-04-10 20:00:05,454: _ready: http://juan:42415/
[xmlrpc][INFO] 2020-04-10 20:00:05,456: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2020-04-10 20:00:05,457: Registering with master node http://tractor:11311/
[rospy.init][INFO] 2020-04-10 20:00:05,555: registered with master
[rospy.rosout][INFO] 2020-04-10 20:00:05,555: initializing /rosout core topic
[rospy.rosout][INFO] 2020-04-10 20:00:05,568: connected to core topic /rosout
[rospy.simtime][INFO] 2020-04-10 20:00:05,576: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.internal][INFO] 2020-04-10 20:00:05,626: topic[/tcpvel] adding connection to [http://juan:45301/], count 0
[rospy.internal][INFO] 2020-04-10 20:00:05,859: topic[/heading] adding connection to [/gps_to_pose_conversion_node], count 0
[rospy.internal][INFO] 2020-04-10 20:00:05,865: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2020-04-10 20:02:04,630: topic[/heading] removing connection to /gps_to_pose_conversion_node
[rospy.internal][INFO] 2020-04-10 20:02:11,868: topic[/heading] adding connection to [/gps_to_pose_conversion_node], count 0
[rospy.internal][INFO] 2020-04-10 20:03:15,830: topic[/heading] removing connection to /gps_to_pose_conversion_node
[rospy.internal][INFO] 2020-04-10 20:03:20,855: topic[/heading] adding connection to [/gps_to_pose_conversion_node], count 0
[rospy.internal][ERROR] 2020-04-10 20:06:13,049: Unable to initiate TCP/IP socket to juan:46055 (http://juan:45301/): Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/usr/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/usr/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][WARNING] 2020-04-10 20:06:14,052: Unknown error initiating TCP/IP socket to juan:46055 (http://juan:45301/): Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2020-04-10 20:06:14,052: topic[/tcpvel] removing connection to http://juan:45301/
[rospy.internal][INFO] 2020-04-10 20:11:12,030: topic[/heading] removing connection to /gps_to_pose_conversion_node
[rospy.core][INFO] 2020-04-10 20:19:11,936: signal_shutdown [signal-2]
[rospy.registration][WARNING] 2020-04-10 20:19:11,944: unclean shutdown
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/rospy/impl/registration.py", line 372, in cleanup
    multi()
  File "/usr/lib/python2.7/xmlrpclib.py", line 1006, in __call__
    return MultiCallIterator(self.__server.system.multicall(marshalled_list))
  File "/usr/lib/python2.7/xmlrpclib.py", line 1243, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1602, in __request
    verbose=self.__verbose
  File "/usr/lib/python2.7/xmlrpclib.py", line 1283, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1311, in single_request
    self.send_content(h, request_body)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1459, in send_content
    connection.endheaders(request_body)
  File "/usr/lib/python2.7/httplib.py", line 1069, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 907, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 869, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 846, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
error: [Errno 101] Network is unreachable

[rospy.internal][INFO] 2020-04-10 20:19:11,945: topic[/rosout] removing connection to /rosout
[rospy.impl.masterslave][INFO] 2020-04-10 20:19:11,945: signal-2
[rospy.core][INFO] 2020-04-10 20:19:12,565: signal_shutdown [atexit]
[rospy.client][INFO] 2020-04-10 20:36:47,127: init_node, name[/heading_compare_node], pid[5022]
[xmlrpc][INFO] 2020-04-10 20:36:47,128: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2020-04-10 20:36:47,128: Started XML-RPC server [http://juan:34937/]
[rospy.init][INFO] 2020-04-10 20:36:47,129: ROS Slave URI: [http://juan:34937/]
[rospy.impl.masterslave][INFO] 2020-04-10 20:36:47,129: _ready: http://juan:34937/
[rospy.registration][INFO] 2020-04-10 20:36:47,130: Registering with master node http://tractor:11311/
[xmlrpc][INFO] 2020-04-10 20:36:47,130: xml rpc node: starting XML-RPC server
[rospy.init][INFO] 2020-04-10 20:36:47,229: registered with master
[rospy.rosout][INFO] 2020-04-10 20:36:47,230: initializing /rosout core topic
[rospy.rosout][INFO] 2020-04-10 20:36:48,842: connected to core topic /rosout
[rospy.simtime][INFO] 2020-04-10 20:36:48,860: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.internal][INFO] 2020-04-10 20:36:51,137: topic[/tcpvel] adding connection to [http://juan:35821/], count 0
[rospy.internal][INFO] 2020-04-10 20:36:52,237: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2020-04-10 20:37:49,956: topic[/heading] adding connection to [/rostopic_5052_1586551069660], count 0
[rospy.internal][INFO] 2020-04-10 20:38:38,683: topic[/heading] adding connection to [/gps_to_pose_conversion_node], count 1
[rospy.internal][INFO] 2020-04-10 20:39:10,742: topic[/heading] removing connection to /gps_to_pose_conversion_node
[rospy.internal][INFO] 2020-04-10 20:39:17,337: topic[/heading] adding connection to [/gps_to_pose_conversion_node], count 1
[rospy.internal][INFO] 2020-04-10 20:39:37,543: topic[/heading] removing connection to /gps_to_pose_conversion_node
[rospy.internal][INFO] 2020-04-10 20:39:48,296: topic[/heading] adding connection to [/gps_to_pose_conversion_node], count 1
[rospy.internal][INFO] 2020-04-10 20:52:23,142: topic[/heading] removing connection to /rostopic_5052_1586551069660
[rosout][WARNING] 2020-04-10 20:52:23,458: Inbound TCP/IP connection failed: connection from sender terminated before handshake header received. 0 bytes were received. Please check sender for additional details.
[rospy.internal][ERROR] 2020-04-10 20:52:23,465: Inbound TCP/IP connection failed:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 321, in _tcp_server_callback
    header = read_ros_handshake_header(sock, StringIO(), buff_size)
  File "/usr/lib/python2.7/dist-packages/rosgraph/network.py", line 365, in read_ros_handshake_header
    raise ROSHandshakeException("connection from sender terminated before handshake header received. %s bytes were received. Please check sender for additional details."%b.tell())
ROSHandshakeException: connection from sender terminated before handshake header received. 0 bytes were received. Please check sender for additional details.

[rospy.internal][ERROR] 2020-04-10 20:53:34,542: Unable to initiate TCP/IP socket to juan:46881 (http://juan:35821/): Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/usr/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/usr/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][WARNING] 2020-04-10 20:53:35,545: Unknown error initiating TCP/IP socket to juan:46881 (http://juan:35821/): Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2020-04-10 20:53:35,545: topic[/tcpvel] removing connection to http://juan:35821/
[rospy.core][INFO] 2020-04-10 20:53:36,033: signal_shutdown [signal-2]
[rospy.registration][WARNING] 2020-04-10 20:53:36,036: unclean shutdown
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/rospy/impl/registration.py", line 372, in cleanup
    multi()
  File "/usr/lib/python2.7/xmlrpclib.py", line 1006, in __call__
    return MultiCallIterator(self.__server.system.multicall(marshalled_list))
  File "/usr/lib/python2.7/xmlrpclib.py", line 1243, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1602, in __request
    verbose=self.__verbose
  File "/usr/lib/python2.7/xmlrpclib.py", line 1283, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1311, in single_request
    self.send_content(h, request_body)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1459, in send_content
    connection.endheaders(request_body)
  File "/usr/lib/python2.7/httplib.py", line 1069, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 907, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 869, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 846, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
error: [Errno 101] Network is unreachable

[rospy.internal][INFO] 2020-04-10 20:53:36,036: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2020-04-10 20:53:36,037: topic[/heading] removing connection to /gps_to_pose_conversion_node
[rospy.impl.masterslave][INFO] 2020-04-10 20:53:36,037: signal-2
[rospy.core][INFO] 2020-04-10 20:53:36,153: signal_shutdown [atexit]
[rospy.client][INFO] 2020-04-10 21:03:43,791: init_node, name[/heading_compare_node], pid[5711]
[xmlrpc][INFO] 2020-04-10 21:03:43,792: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2020-04-10 21:03:43,792: Started XML-RPC server [http://juan:33407/]
[rospy.init][INFO] 2020-04-10 21:03:43,793: ROS Slave URI: [http://juan:33407/]
[rospy.impl.masterslave][INFO] 2020-04-10 21:03:43,793: _ready: http://juan:33407/
[rospy.registration][INFO] 2020-04-10 21:03:43,794: Registering with master node http://tractor:11311/
[xmlrpc][INFO] 2020-04-10 21:03:43,794: xml rpc node: starting XML-RPC server
[rospy.init][INFO] 2020-04-10 21:03:43,893: registered with master
[rospy.rosout][INFO] 2020-04-10 21:03:43,894: initializing /rosout core topic
[rospy.rosout][INFO] 2020-04-10 21:03:43,907: connected to core topic /rosout
[rospy.simtime][INFO] 2020-04-10 21:03:43,917: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.internal][INFO] 2020-04-10 21:03:44,013: topic[/tcpvel] adding connection to [http://juan:35325/], count 0
[rospy.internal][INFO] 2020-04-10 21:03:44,186: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2020-04-10 21:04:18,835: topic[/heading] adding connection to [/rostopic_5735_1586552658538], count 0
[rospy.internal][INFO] 2020-04-10 21:05:11,627: topic[/heading] adding connection to [/gps_to_pose_conversion_node], count 1
[rospy.internal][INFO] 2020-04-10 21:35:34,624: topic[/heading] removing connection to /rostopic_5735_1586552658538
[rosout][WARNING] 2020-04-10 21:35:34,979: Inbound TCP/IP connection failed: connection from sender terminated before handshake header received. 0 bytes were received. Please check sender for additional details.
[rospy.internal][ERROR] 2020-04-10 21:35:34,982: Inbound TCP/IP connection failed:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 321, in _tcp_server_callback
    header = read_ros_handshake_header(sock, StringIO(), buff_size)
  File "/usr/lib/python2.7/dist-packages/rosgraph/network.py", line 365, in read_ros_handshake_header
    raise ROSHandshakeException("connection from sender terminated before handshake header received. %s bytes were received. Please check sender for additional details."%b.tell())
ROSHandshakeException: connection from sender terminated before handshake header received. 0 bytes were received. Please check sender for additional details.

[rospy.internal][ERROR] 2020-04-10 21:36:21,461: Unable to initiate TCP/IP socket to juan:38175 (http://juan:35325/): Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/usr/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/usr/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.core][INFO] 2020-04-10 21:36:22,390: signal_shutdown [signal-2]
[rospy.internal][WARNING] 2020-04-10 21:36:22,462: Unknown error initiating TCP/IP socket to juan:38175 (http://juan:35325/): Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2020-04-10 21:36:22,463: topic[/tcpvel] removing connection to http://juan:35325/
[rospy.registration][WARNING] 2020-04-10 21:36:24,534: unclean shutdown
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/rospy/impl/registration.py", line 372, in cleanup
    multi()
  File "/usr/lib/python2.7/xmlrpclib.py", line 1006, in __call__
    return MultiCallIterator(self.__server.system.multicall(marshalled_list))
  File "/usr/lib/python2.7/xmlrpclib.py", line 1243, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1602, in __request
    verbose=self.__verbose
  File "/usr/lib/python2.7/xmlrpclib.py", line 1283, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1311, in single_request
    self.send_content(h, request_body)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1459, in send_content
    connection.endheaders(request_body)
  File "/usr/lib/python2.7/httplib.py", line 1069, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 907, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 869, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 846, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
error: [Errno 113] No route to host

[rospy.internal][INFO] 2020-04-10 21:36:24,535: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2020-04-10 21:36:24,535: topic[/heading] removing connection to /gps_to_pose_conversion_node
[rospy.impl.masterslave][INFO] 2020-04-10 21:36:24,536: signal-2
[rospy.core][INFO] 2020-04-10 21:36:25,051: signal_shutdown [atexit]
